# Training parameters
train:
  test_size: 0.1
  random_state: 1
  cv_folds: 5
  n_trials: 10

# XGBoost model parameters
model:
  objective: "reg:squarederror"
  random_state: 1
  eval_metric: "rmse"
  tree_method: "hist"

# Hyperparameter search space
param_dist:
  n_estimators: [500, 1000]
  learning_rate: [0.01, 0.1]
  max_depth: [6, 8, 10]
  subsample: [0.7]
  colsample_bytree: [0.8]
  reg_alpha: [0]
  reg_lambda: [1]


